***Introduction***: 
    In this project, I am looking for the best neighborhood in Pittsburgh. By using data sets, we will analyze different criterias from 3 different datasets to show subjectively which is the "best" neighborhood in Pittsburgh. For me, i am using the 2020 Census Redistricting Data and specifically using the  City of Pittsburgh Neighborhood Population 2020. My metric that I came up with is DIVERISTY. I believe the more diverse the population, the btter the neighborhood.
    
    
The Metric: Describe your metric, what features are you measuring. What datasets are you using?
The Best Neighborhood: Apply the metric from the previous section to determine the best neighborhood in Pittsburgh. Beyond just executing code, provide a narrative about why you think this is the best neighborhood. Incorporate a data visualization, perhaps to rank all of the neighborhoods or show a neighborhood’s best-ness over time. The key is to make a data driven argument.
Conclusion: Reflect on how the data driven determination of “best neighborhood” is the same or different from your personal favorite neighborhood. Each member of the group should write their own response to this.

***The Metric***: My metric is based on population of the people of color. I am using population based on race in each neighborhood. I am using City of Pittsburgh Neighborhood Population 2020.

First import pandas and import data

In [3]:
import pandas as pd

#import dataset
market = pd.read_csv("spmkt.csv")
market.head(5)

,Client ID,Name,Legal Name,Start Date,Street #,Street Name,State,Zip,Lat,Lon,Accuracy,Category
0,200504200001,BP / Bloomfield,Jay Oil Corp,4/15/2005,4006,Liberty Ave,PA,15224.0,40.462645,-79.956820,9.0,Convenience Store
1,201511040005,Ez Energy #303/7Eleven #36183H,Neelkanth Ansh Enterprises Inc,10/26/2015,209,Ohio River Blvd,PA,15143.0,40.545418,-80.194152,9.0,Convenience Store
2,201212130003,EZ Energy #311 / 7 Eleven #36191H,7 Eleven Inc,12/3/2012,8136,Ohio River Blvd,PA,15202.0,40.510522,-80.094268,9.0,Convenience Store
3,201211190006,Getgo #3646 / Crafton - Ingram,Giant Eagle Inc,11/15/2012,280,Crafton Ingram Shopping circle,PA,15205.0,41.203322,-77.194525,3.0,Convenience Store
4,53583,Mt NeBlvd Texaco,Mt NeBlvd Texaco,6/2/1995,1706,Mt Nebo Rd,PA,15143.0,40.553281,-80.109158,8.0,Convenience Store